<?
$PERM["local"]["2"]="X";
$PERM["local"]["6"]="X";
$PERM["local"]["3"]="X";
$PERM["local"]["4"]="X";
$PERM["local"]["7"]="X";
$PERM["local"]["5"]="X";
$PERM["local"]["8"]="X";
$PERM["local"]["*"]="X";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["/"]["*"]="R";
?>